name: Docker Build and Push
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and push to GitHub Container Registry
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set VERSION and TAG
        run: |
          TAG="${GITHUB_REF#refs/*/}" # ex.: v29.2.knots20251110-1
          VERSION="${TAG#v}"          # Remove leading 'v' (ex.: 29.2.knots20251110-1)
          VERSION="${VERSION%%-*}"    # Remove -metadata (p.ex. 29.2.knots20251110)
          VERSION="${VERSION%.*}"     # Remove trailing .knotsDATE (ex.: 29.2)
          MAJOR="${VERSION%%.*}"      # Extract major version (ex.: 29)

          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "MAJOR=${MAJOR}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Setup Docker buildx
        run: docker buildx create --use

      - name: Run Docker buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ env.VERSION }} \
            --tag ghcr.io/${{ github.repository }}:${{ env.TAG }} \
            --tag ghcr.io/${{ github.repository }}:v${{ env.VERSION }} \
            --tag ghcr.io/${{ github.repository }}:v${{ env.MAJOR }} \
            --tag ghcr.io/${{ github.repository }}:latest \
            --push .
